import pathlib
import tkinter as tk
import tkinter.ttk as ttk

PROJECT_PATH = pathlib.Path(__file__).parent
PROJECT_UI = PROJECT_PATH / "newproject"


class NewprojectWidget(ttk.Frame):
    def __init__(self, master=None, **kw):
        super(NewprojectWidget, self).__init__(master, **kw)
        self.frame2 = ttk.Frame(self)
        self.frame3 = ttk.Frame(self.frame2)
        self.frame4 = ttk.Frame(self.frame3)
        self.button1 = ttk.Button(self.frame4)
        self.button1.configure(text="button1")
        self.button1.pack(side="top")
        self.frame4.configure(height="200", width="200")
        self.frame4.grid(column="0", row="0")
        self.frame3.columnconfigure("0", minsize="1200")
        self.text1 = tk.Text(self.frame3)
        self.text1.configure(font="{URW Chancery L} 12 {}", height="10", width="50")
        self.text1.grid(
            column="0", columnspan="10", padx="10", pady="10", row="1", rowspan="10"
        )
        self.frame3.rowconfigure("1", minsize="600")
        self.frame5 = ttk.Frame(self.frame3)
        self.frame5.configure(height="200", width="200")
        self.frame5.grid(column="0", row="2")
        self.button2 = ttk.Button(self.frame3)
        self.button2.configure(text="button2")
        self.button2.grid(column="0", row="3")
        self.button3 = ttk.Button(self.frame3)
        self.button3.configure(text="button3")
        self.button3.grid(column="0", row="4")
        self.button4 = ttk.Button(self.frame3)
        self.button4.configure(text="button4")
        self.button4.grid(column="0", row="5", sticky="e")
        self.button5 = ttk.Button(self.frame3)
        self.button5.configure(text="button5")
        self.button5.grid(column="0", row="6")
        self.button6 = ttk.Button(self.frame3)
        self.button6.configure(text="button6")
        self.button6.grid(column="0", row="7", sticky="w")
        self.button7 = ttk.Button(self.frame3)
        self.button7.configure(text="button7")
        self.button7.grid(column="0", row="8")
        self.button8 = ttk.Button(self.frame3)
        self.button8.configure(text="button8")
        self.button8.grid(column="0", row="9")
        self.button9 = ttk.Button(self.frame3)
        self.button9.configure(text="button9")
        self.button9.grid(column="0", row="10")
        self.button10 = ttk.Button(self.frame3)
        self.button10.configure(text="button10")
        self.button10.grid(column="0", row="11")
        self.button11 = ttk.Button(self.frame3)
        self.button11.configure(text="button11")
        self.button11.grid(column="0", row="12")
        self.button12 = ttk.Button(self.frame3)
        self.button12.configure(text="button12")
        self.button12.grid(column="0", row="13")
        self.button13 = ttk.Button(self.frame3)
        self.button13.configure(text="button13")
        self.button13.grid(column="0", row="14")
        self.button14 = ttk.Button(self.frame3)
        self.button14.configure(text="button14")
        self.button14.grid(column="0", row="15")
        self.button15 = ttk.Button(self.frame3)
        self.button15.configure(text="button15")
        self.button15.grid(column="0", row="16")
        self.button16 = ttk.Button(self.frame3)
        self.button16.configure(text="button16")
        self.button16.grid(column="0", row="17")
        self.text2 = tk.Text(self.frame3)
        self.text2.configure(height="10", width="50")
        self.text2.grid(column="0", row="18")
        self.scrollbar1 = ttk.Scrollbar(self.frame3)
        self.scrollbar1.configure(orient="horizontal")
        self.scrollbar1.grid(column="0", row="19")
        self.scrollbar2 = ttk.Scrollbar(self.frame3)
        self.scrollbar2.configure(orient="horizontal")
        self.scrollbar2.grid(column="0", row="20")
        self.frame3.configure(height="200", width="200")
        self.frame3.grid(column="0", row="0")
        self.frame2.configure(height="200", width="200")
        self.frame2.grid(column="0", columnspan="10", row="0", sticky="nw")


if __name__ == "__main__":
    root = tk.Tk()
    widget = NewprojectWidget(root)
    widget.pack(expand=True, fill="both")
    root.mainloop()
